version: "3.9"
services:
  postgresdb:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  railpapp:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./src:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgresdb
volumes:
  postgres-data:
    driver: local
